### ISSUE TITLE
Merge data from various sources into a single json for ease of use.

### ISSUE THREAD

**Issue by shreyapandit** [ASL-LEX/asl-lex#1]
Data Sources:

- Node and Edge data from Heroku app
- OSF data
- CSVs sent by Naomi herself.

Going forward, we wish to merge this data into a single place for our use. The nodes.json and edges.json are the files that we wish to merge this data into since they have some graphics parameters that are prior-defined and we wish to keep (video-URL etc)

Below is one node for the NodeData used in the viz (for filtering and displaying on the Sign Data Tab):

{

**Custom - Retain this as is**
**TODO: we should ask Naomi how these space coordinates, video URLS were generated**
"EntryID":"zipper",
"x":-345.3912354,
"y":-843.538208,"
id":"zipper","
color":"rgb(58,82,187)",
"size":11.49020958,
"video":"KQROUeeFHGg",
"attributes":{"original_color":"rgb(58,82,187)",
"original_size":11.49020958,
"LemmaID":"zipper","
******************************************************
**OSF- These remain as is for now**: 

Sign Frequency (M)":3.148,"
Sign Frequency (SD)":1.61,
"Sign Frequency (Z)":-0.556203152,
"Sign Frequency (N)":27,
"Percent Unknown":"0.00%",
"Sign Frequency (M, Native)":2.875,
"Sign Frequency (SD, Native)":1.31,
"Sign Frequency (Z, Native)":-0.725565683,
"Sign Frequency (N, Native)":16,
"Percent Unknown (Native)":"0.00%",
"Lexical Class":"Noun",
"Initialized":0, **-> Present in phonologyCoding.csv**
"Iconicity (M)":6.394,
"Iconicity (SD)":2.025,
"Iconicity (Z)":1.737,
"Iconicity (N)":33,
*TODO what are these 3 below? And how are they calculated?*
"Sign Onset (ms)":633.97,
"Sign Offset (ms)":1668.34,
"Sign Length (ms)":1034.37,"
Clip Length (ms)":2202.2,
*TODO: How are they calculated?*
"Maximal Neighborhood Density":9,
"Minimal Neighborhood Density":689,
"Parameter-Based Neighborhood Density":6,
"Sign Type Frequency":78,"
Movement Frequency":354,"
Major Location Frequency":100,
"Minor Location Frequency":18,
"Selected Fingers Frequency":455,
"Flexion Frequency":82,
"Handshape Frequency":354}
}
**OSF-These need to be updated wth new values from phonologyCoding.csv **
"Compound":0,  **-> Present in phonologyCoding.csv**
"Fingerspelled Loan Sign":0,**-> Present in phonologyCoding.csv**
"SignType":"AsymmetricalSameHandshape",**-> Present in phonologyCoding.csv**
"Movement":"BackAndForth", **-> Present in phonologyCoding.csv in 5 subtypes**
"Major Location":"Body", **-> Present in phonologyCoding.csv in 5 subtypes**
"Minor Location":"TorsoBottom", **-> Present in phonologyCoding.csv in 5 subtypes**
"Selected Fingers":"imrp", **-> Present in phonologyCoding.csv in 5 subtypes**
"Flexion":7, **-> Present in phonologyCoding.csv in 5 subtypes**

**To add to each sign: New features which are Extra params introduced by phonologycoding.csv:**
Code	
NumberOfMorphemes.2.0
SecondMinorLocation.2.0
Contact.2.0
ThumbPosition.2.0	
ThumbContact.2.0	
FlexionChange.2.0	
Spread.2.0	
SpreadChange.2.0	
UlnarRotation.2.0	
NonDominantHandshape.2.0	
SignTypeM2.2.0	
MajorLocationM2.2.0	
MinorLocationM2.2.0	
SecondMinorLocationM2.2.0	
MovementM2.2.0	
ContactM2.2.0	
SelectedFingersM2.2.0	
ThumbPositionM2.2.0	
ThumbContactM2.2.0	
FlexionM2.2.0	
FlexionChangeM2.2.0
SpreadM2.2.0
SpreadChangeM2.2.0
UlnarRotationM2.2.0
HandshapeM2.2.0	
NonDominantHandshapeM2.2.0	
SignTypeM3.2.0	
MajorLocationM3.2.0	
MinorLocationM3.2.0	
SecondMinorLocationM3.2.0	
MovementM3.2.0	
ContactM3.2.0	
SelectedFingersM3.2.0	
ThumbPositionM3.2.0	
ThumbContactM3.2.0	
FlexionM3.2.0	
FlexionChangeM3.2.0	
SpreadM3.2.0	
SpreadChangeM3.2.0	
UlnarRotationM3.2.0	
HandshapeM3.2.0	
NonDominantHandshapeM3.2.0	
SignTypeM4.2.0	
MajorLocationM4.2.0	
MinorLocationM4.2.0	
SecondMinorLocationM4.2.0	
MovementM4.2.0	
ContactM4.2.0	
SelectedFingersM4.2.0	
ThumbPositionM4.2.0	
ThumbPositionM5.2.0	
FlexionM4.2.0	
FlexionChangeM4.2.0	
SpreadM4.2.0	
SpreadChangeM4.2.0	
UlnarRotationM4.2.0	
HandshapeM4.2.0	
NonDominantHandshapeM4.2.0	
SignTypeM5.2.0	
MajorLocationM5.2.0	
MinorLocationM5.2.0	
SecondMinorLocationM5.2.0	
MovementM5.2.0	
ContactM5.2.0	
SelectedFingersM5.2.0	
ThumbPositionM6.2.0	
ThumbContactM4.2.0	
FlexionM5.2.0	
FlexionChangeM5.2.0	
SpreadM5.2.0	
SpreadChangeM5.2.0	
UlnarRotationM5.2.0	
HandshapeM5.2.0	
NonDominantHandshapeM5.2.0	
SignTypeM6.2.0	
MajorLocationM6.2.0	
MinorLocationM6.2.0	
SecondMinorLocationM6.2.0	
MovementM6.2.0
ContactM6.2.0	
SelectedFingersM6.2.0	
ThumbContactM5.2.0	
ThumbContactM6.2.0	
FlexionM6.2.0	
FlexionChangeM6.2.0	
SpreadM6.2.0	
SpreadChangeM6.2.0	
UlnarRotationM6.2.0	
HandshapeM6.2.0	
NonDominantHandshapeM6.2.0
*************************************************
Edge Data - We need to use as is until we dont have user defined edges. In any case default viz should use these edges.
**TODO ask how these edges and colors were decided and if they have any significance**

**Comment by shreyapandit** [comment]
- [ ] For columns for which PhologyCoding.csv has new data, replace that
- [ ] For other columns of OSF, that data stays as is.
- [ ] New columns from  PhologyCoding.csv to be added. 

Final matrix should look like SignData.csv but with many more columns.

**Comment by shreyapandit** [comment]
[data.zip](https://github.com/ASL-LEX/asl-lex/files/3230649/data.zip)

**Comment by shreyapandit** [comment]
There should be a python script to do all the above for reproducibility for the next time.
